//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tos.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   適切なユーザーでログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthenticationErrorMessage {
            get {
                return ResourceManager.GetString("AuthenticationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   適切な権限のあるユーザーでログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizedErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページにアクセスする権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizedErrorMessageTitle {
            get {
                return ResourceManager.GetString("AuthorizedErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Buhin_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuhinDownload {
            get {
                return ResourceManager.GetString("BuhinDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _BuhinUploadError_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuhinUploadError {
            get {
                return ResourceManager.GetString("BuhinUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CsvExtension {
            get {
                return ResourceManager.GetString("CsvExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードでエラーが発生しています。
        ///アップロードしたファイルの下記のエラーを修正して再度アップロードしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSVUploadError {
            get {
                return ResourceManager.GetString("CSVUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbSaveErrorMessage {
            get {
                return ResourceManager.GetString("DbSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに他のユーザーがこのデータを変更しています。最新のデータを取得してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DbUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DbUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XXXXX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultPassword {
            get {
                return ResourceManager.GetString("DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shift-JIS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー値 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorValue {
            get {
                return ResourceManager.GetString("ErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelExtension {
            get {
                return ResourceManager.GetString("ExcelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルダウンロードで出力する項目が選択されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileDownloadSelectErrorMessage {
            get {
                return ResourceManager.GetString("FileDownloadSelectErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveErrorMessage {
            get {
                return ResourceManager.GetString("FileSaveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを保存しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSaveSuccessMessage {
            get {
                return ResourceManager.GetString("FileSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルサイズが{0}KB以上は保存できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角アルファベットのみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAlphabetError {
            get {
                return ResourceManager.GetString("InvalidAlphabetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角アルファベット・数字のみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAlphabetNumberError {
            get {
                return ResourceManager.GetString("InvalidAlphabetNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ０/１もしくはTrue/Falseで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidBitFormatError {
            get {
                return ResourceManager.GetString("InvalidBitFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列数が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidColumnSizeTextFieldFile {
            get {
                return ResourceManager.GetString("InvalidColumnSizeTextFieldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付フォーマットで指定してください。形式：{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidDateFormatError {
            get {
                return ResourceManager.GetString("InvalidDateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数字で指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidDigitsFormatError {
            get {
                return ResourceManager.GetString("InvalidDigitsFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角アルファベット・数字・記号のみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHankakuEiSuKigoError {
            get {
                return ResourceManager.GetString("InvalidHankakuEiSuKigoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角のみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHankakuError {
            get {
                return ResourceManager.GetString("InvalidHankakuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角カナのみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidHankakuKanaError {
            get {
                return ResourceManager.GetString("InvalidHankakuKanaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数値で指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidIntegerFormatError {
            get {
                return ResourceManager.GetString("InvalidIntegerFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値で指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidNumberFormatError {
            get {
                return ResourceManager.GetString("InvalidNumberFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数部{0}桁、小数点以下{1}桁までの数値を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPointLengthFormatError {
            get {
                return ResourceManager.GetString("InvalidPointLengthFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDまたはパスワードが違います。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidUserIdOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDまたはパスワードが違います。もしくは有効期限が切れています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidUserIdOrPasswordOrExpire {
            get {
                return ResourceManager.GetString("InvalidUserIdOrPasswordOrExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角のみで指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidZenkakuError {
            get {
                return ResourceManager.GetString("InvalidZenkakuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WinLogin.aspx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LOGON_USER に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogonUser {
            get {
                return ResourceManager.GetString("LogonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Mitsumori_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MitsumoriDownload {
            get {
                return ResourceManager.GetString("MitsumoriDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Template.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MitsumoriExcelTemplateFile {
            get {
                return ResourceManager.GetString("MitsumoriExcelTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _MitsumoriUploadError_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MitsumoriUploadError {
            get {
                return ResourceManager.GetString("MitsumoriUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当データが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoDataExsists {
            get {
                return ResourceManager.GetString("NoDataExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが指定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoFileAttachmentMessage {
            get {
                return ResourceManager.GetString("NoFileAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルサイズが 0KB のためアップロードできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoFileDataMessage {
            get {
                return ResourceManager.GetString("NoFileDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたファイルが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoFileExists {
            get {
                return ResourceManager.GetString("NoFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力されたコードがマスタに存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoKeyDataExsists {
            get {
                return ResourceManager.GetString("NoKeyDataExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードの変更に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotChangePassword {
            get {
                return ResourceManager.GetString("NotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NULL は許可されません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotNullAllow {
            get {
                return ResourceManager.GetString("NotNullAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アップロードするデータが1件もありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoUploadDataError {
            get {
                return ResourceManager.GetString("NoUploadDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインしたユーザーの社員コードで社員マスタに情報が存在しませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoUserExists {
            get {
                return ResourceManager.GetString("NoUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumberToBoolean {
            get {
                return ResourceManager.GetString("NumberToBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が指定桁数を超えています。半角{0}桁、全角{1}桁までで設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfLengthTextField {
            get {
                return ResourceManager.GetString("OutOfLengthTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が範囲を超えています。{0} から {1} までの数値を設定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutOfRangeTextField {
            get {
                return ResourceManager.GetString("OutOfRangeTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プライマリキー制約違反です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrimaryKeyViolation {
            get {
                return ResourceManager.GetString("PrimaryKeyViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルダウンロード処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RaiseFileDownloadServerError {
            get {
                return ResourceManager.GetString("RaiseFileDownloadServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルアップロード処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RaiseFileUploadServerError {
            get {
                return ResourceManager.GetString("RaiseFileUploadServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷処理中にサーバーで不明なエラーが発生しました。システム管理者に問い合わせしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RaiseReportServerError {
            get {
                return ResourceManager.GetString("RaiseReportServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordNumber {
            get {
                return ResourceManager.GetString("RecordNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   __key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestClientKeyName {
            get {
                return ResourceManager.GetString("RequestClientKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須の項目です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequiredTextField {
            get {
                return ResourceManager.GetString("RequiredTextField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;meta http-equiv=&apos;content-type&apos; content=&apos;text/html; charset=UTF-8&apos; /&gt;
        ///        &lt;script type=&apos;text/javascript&apos;&gt;
        ///            if(window.parent &amp;&amp; window.parent.postMessage){{
        ///                    window.parent.postMessage(&apos;{0}&apos;,&apos;{1}&apos;);
        ///                }}
        ///        &lt;/script&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div class=&apos;key&apos;&gt;{2}&lt;/div&gt; 
        ///        &lt;div class=&apos;result&apos;&gt;{3}&lt;/div&gt; 
        ///        &lt;div class=&apos;message&apos;&gt;{4}&lt;/div&gt; 
        ///        &lt;div class=&apos;data&apos;&gt;{5}&lt;/div&gt; 
        ///    &lt;/body&gt;
        ///&lt;/html&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResponseHtmlFormat {
            get {
                return ResourceManager.GetString("ResponseHtmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MixedSecurity.ReturnUrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReturnUrl {
            get {
                return ResourceManager.GetString("ReturnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サービスでエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明なエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同一キーのデータが既に存在します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidationKey {
            get {
                return ResourceManager.GetString("ValidationKey", resourceCulture);
            }
        }
    }
}
