//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kentosho
    {
        public int no_kento { get; set; }
        public int no_mitsumori { get; set; }
        public Nullable<int> no_komoku { get; set; }
        public int cd_buhin { get; set; }
        public string nm_komoku { get; set; }
        public Nullable<int> su_suryo { get; set; }
        public Nullable<decimal> kin_shiire_tanka { get; set; }
        public Nullable<System.DateTimeOffset> dt_create { get; set; }
        public string cd_create { get; set; }
        public Nullable<System.DateTimeOffset> dt_update { get; set; }
        public string cd_update { get; set; }
        public byte[] ts { get; set; }
    }
}
