//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int no_news { get; set; }
        public string nm_title { get; set; }
        public string nm_content { get; set; }
        public System.DateTime dt_news { get; set; }
        public string level { get; set; }
        public Nullable<System.DateTimeOffset> dt_create { get; set; }
        public string cd_create { get; set; }
        public Nullable<System.DateTimeOffset> dt_update { get; set; }
        public string cd_update { get; set; }
        public byte[] ts { get; set; }
    }
}
