//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tos.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public System.DateTime dt_product { get; set; }
        public int su_shukka { get; set; }
        public int su_keikaku { get; set; }
        public int su_jisseki { get; set; }
        public int su_zaiko { get; set; }
        public Nullable<System.DateTimeOffset> dt_create { get; set; }
        public string cd_create { get; set; }
        public Nullable<System.DateTimeOffset> dt_update { get; set; }
        public string cd_update { get; set; }
        public byte[] ts { get; set; }
    }
}
